name = "houserenoai"
compatibility_date = "2024-11-03"
pages_build_output_dir = "dist"

[env.production]
name = "houserenoai"

[env.production.vars]
VITE_API_URL = "https://houserenovators-api.fly.dev"
VITE_ENV = "production"
VITE_ENABLE_DEBUG = "false"